service: 
  name: circleci-key-rotator

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, 'us-east-1'}
  profile: ${opt:profile, 'default'}
  memorySize: 128
  environment:
    BUCKET: !Ref JobBucket
  iamRoleStatements:
    - Effect: Allow
      Action:
        - iam:ListAccessKeys
        - iam:DeleteAccessKey
        - iam:CreateAccessKey
        - iam:UpdateAccessKey
      Resource: 
        - arn:aws:iam::*:user/*
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:ListBucket
      Resource:
        - !Join ["", ["arn:aws:s3:::", !Ref JobBucket]]
        - !Join ["", ["arn:aws:s3:::", !Ref JobBucket, "/*"]]
        
functions:
  rotate:
    handler: src/handler.rotateKeys
    description: Rotates the Access Keys for CircleCI
    events:
      - schedule: cron(0 4 * * ? *)

resources:
  Resources:
    JobBucket:
      Type: AWS::S3::Bucket
      Properties: 
        AccessControl: Private

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-optimize
