service: 
  name: ${opt:projectName}-circleci-key-rotator

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, 'eu-west-2'}
  memorySize: 128
  environment:
    VCS_PROVIDER: ${opt:vcs, 'github'}
    VCS_USER: ${opt:vcsUser, 'EconomistDigitalSolutions'}
    IAM_USER: ${opt:awsUser}
    PROJECT_NAME: ${opt:projectName}
    API_TOKEN: ${opt:apiToken, ''}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - iam:ListAccessKeys
        - iam:GetAccessKeyLastUsed
        - iam:DeleteAccessKey
        - iam:CreateAccessKey
        - iam:UpdateAccessKey
      Resource: 
        - arn:aws:iam::${opt:awsAccountId}:user/${opt:awsUser}
        
functions:
  rotate:
    handler: src/handler.rotateKeys
    events:
      - schedule: cron(0 10 * * ? *)

plugins:
  - serverless-plugin-typescript
  - serverless-offline
