service: 
  name: ${opt:projectName}-circleci-key-rotator

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, 'us-east-1'}
  profile: ${opt:profile}
  memorySize: 128
  environment:
    # KeyRotator 
    IAM_USER: ${opt:awsUser}
    # CircleCI API
    VCS_PROVIDER: ${opt:vcs, 'github'}
    VCS_USER: ${opt:vcsUser, 'EconomistDigitalSolutions'}
    PROJECT_NAME: ${opt:projectName}
    API_TOKEN: ${opt:apiToken }
    # CircleCI Env Vars
    ACCESS_KEY_NAME: ${opt:accessKeyName, 'AWS_ACCESS_KEY_ID'}
    SECRET_KEY_NAME: ${opt:secretKeyName, 'AWS_SECRET_ACCESS_KEY'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - iam:ListAccessKeys
        - iam:DeleteAccessKey
        - iam:CreateAccessKey
        - iam:UpdateAccessKey
      Resource: 
        - arn:aws:iam::${opt:awsAccountId}:user/${opt:awsUser}
        
functions:
  rotate:
    handler: src/handler.rotateKeys
    description: Rotates the Access Keys for ${opt:awsUser}
    events:
      - schedule: cron(0 4 * * ? *)

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-optimize
