version: 2
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-browsers-legacy
    steps:
      - checkout
      - run: 
          name: install
          command: 'sudo npm install'
      - run:
          name: build
          command: 'npm run build'
  test:
    docker:
      - image: circleci/node:chakracore-browsers-legacy
    steps:
      - checkout
      - run: 
          name: install
          command: 'sudo npm install'
      - run:
          name: test
          command: 'npm test'